name: $(Build.SourceBranchName)-$(date:yyyyMMdd)$(rev:.r)

trigger:
- develop

pr:
- develop

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  disable.coverage.autogenerate: 'true'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: 'test'
    projects: '**/*Tests.csproj'
    publishTestResults: true
    arguments: '--configuration $(buildConfiguration) --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=$(Build.SourcesDirectory)\TestResults\ /p:Threshold=55'

- task: reportgenerator@4
  displayName: Report
  inputs:
    reports: '$(Build.SourcesDirectory)\TestResults\coverage.cobertura.xml'
    targetdir: '$(Build.SourcesDirectory)\CodeCoverageReport'
    reporttypes: 'HtmlInline_AzurePipelines;Cobertura'

- task: PublishCodeCoverageResults@1
  displayName: Publish Report
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(Build.SourcesDirectory)\CodeCoverageReport\Cobertura.xml'
    reportDirectory: '$(Build.SourcesDirectory)\CodeCoverageReport'
    failIfCoverageEmpty: true

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  inputs:
    Contents: |
     **\*.nuspec
     **\bin\Release\NET35\GongSolutions.Wpf.DragDrop.dll
     **\bin\Release\NET35\GongSolutions.Wpf.DragDrop.xml
     **\bin\Release\NET35\GongSolutions.Wpf.DragDrop.pdb
     **\bin\Release\NET4\GongSolutions.Wpf.DragDrop.dll
     **\bin\Release\NET4\GongSolutions.Wpf.DragDrop.xml
     **\bin\Release\NET4\GongSolutions.Wpf.DragDrop.pdb
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'gong-wpf-dragdrop'
    publishLocation: 'Container'
