trigger: none

pool:
  vmIamge: 'windows-latest'
  
variables:
  Major: 1
  Minor: 0
  Revision: $[counter(format('{0}-{1}', variables['Major'], variables['Minor']), 0)]
  PackageVersion: $[format('{0}.{1}.{2}', variables['Major'], variables['Minor'], variables['Revision'])]

steps:
- task: DownloadPipelineArtifact@2
  displayName: Download package artifacts
  inputs:
    buildType: 'specific'
    project: 'a119dd29-1840-4811-bac7-d797f815186b'
    definition: '77'
    specificBuildWithTriggering: false
    buildVersionToDownload: 'latestFromBranch'
    branchName: 'refs/heads/develop'
    artifactName: 'gong-wpf-dragdrop'
    targetPath: '$(Pipeline.Workspace)'

- task: NuGetCommand@2
  inputs:
    command: pack
    packagesToPack: 'GongSolutions.Wpf.DragDrop/GongSolutions.Wpf.DragDrop.nuspec'
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'PackageVersion'
    basePath: '$(Pipeline.Workspace)/gong-wpf-dragdrop/GongSolutions.Wpf.DragDrop'
    packDestination: '$(Build.ArtifactStagingDirectory)/package'
    
- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/package/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/package/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'a0b0aaaa-c5cc-43c6-af3e-60bcbbc1f245'